language: go

go:
  - "1.12"

services:
  - docker

jobs:
  include:
    - stage: E2E Tests
      before_script:
        # Download and install KinD
        - go get sigs.k8s.io/kind
        # Create a new Kubernetes cluster using KinD
        - kind create cluster
        # Set KUBECONFIG environment variable
        - export KUBECONFIG="$(kind get kubeconfig-path)"
        # Install ginkgo to go path
        - go get github.com/onsi/ginkgo/ginkgo
      script:
        - make
        - make test