language: go
go:
  - '1.14'
services:
  - docker

env:
  - GO111MODULE=on

install: true

script: go test -v -mod=vendor ./...

jobs:
  include:
    - stage: E2E Tests
      before_script:
        # install upx for compression
        - curl -Lo upx.tar.xz https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz && tar xvf upx.tar.xz
        - sudo mv upx-3.95-amd64_linux/upx /usr/local/bin
        # start k8s cluster in KinD
        - go get sigs.k8s.io/kind
        - kind create cluster
        - kind get kubeconfig > kubeconfig
        - export KUBECONFIG=$PWD/kubeconfig
        # install ginkgo for testing
        - go get github.com/onsi/ginkgo/ginkgo@v1.8.0
      script:
        - make test
before_deploy:
  - make compress-all
deploy:
  provider: releases
  api_key:
    secure: UJbIwthI6H6xHfmUemngTuZ2jPjwQrfC6tMs6NSgOZjKYIftLMVUVzte09PYSuFqxmAj+riTyGSgO7mXCrnQbVZSQ2S+14V27jORnBc6Ee6fQGcibWju2aim2Ww0NQRyjQ5PN3eh65/wxTF08WQgCySxARIZawsiUwp81jS9f7Eiu+ZfX3sNYKSM1gZpXYGZrsHBdcAmHd4rlp3CP3YlaNsRe8An4ZlUEc9emQNFwmFLz+J2xaLR+36PfhX/7GT9bPLoqbx+ibAwGEaWoSdhiXViPk/lRcR2H+HNjW0p7BI10eQNvAJfW/+rIhkQM2bjpD8I1v3GtLDwjF+6RfXg+khC1DjX6RU0RfNk1d0KffebSwLxKrwVQGHoLjJxRn9KegfSPZZfVc8Tg1F6pg9X19YApYI+f5HUDxPubVLgwr9hU1PUJyV7JBrchJ3R6ZPkev3dOAnqx60m29H/Zsy3NlYjQoSfAU6Bs/aBwx5bNjd/Y9GBTCVo2vcroq6taIFl6DO94fmDuXA09WDB9iUwEdTakzBHcpLlXopA104SHjBT9gn8oY9Vj82Xv8duUzJ7xHjm7er8aSoeQb5ZJ+unQNoW4yYIQ+0dyZak6Zg9DqpkTVX3nEtExic96iHkXxXf1q4ctXc0u4WJf6UqGSj7uFnmlsHnIyej+uEZDPDW6A0=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
